### ISSUE TITLE
crashing when opening the menu of the mod

### ISSUE THREAD

**Issue by binni0r** [ReviversMC/too-many-binds#37]
i downloaded 1.19.3 version of this mod on 1.19.4, minecraft lauched normally, but when i press the button that opens this mod's menu, the game crashes.

**Comment by thefirethirteen** [comment]
Can you try using a newer (not yet released) version?
Steps here: https://github.com/ReviversMC/too-many-binds/pull/36#issuecomment-1500906464.

Please report back. :)

**Comment by NebelNidas** [comment]
An official update to 1.19.4 has been released yesterday :)

**Comment by binni0r** [comment]
thank you very much!
